name: Publish on firefox store
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release tag'
        required: true
        default: 'v1.0.0'

env:
  PACKAGE_NAME: drfrf-${{ github.event.inputs.tag }}.xpi

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Pack extension
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: build
          verbose: true
          filename: ${{ env.PACKAGE_NAME }}
          # ignoreFiles: [".git/*", ".github/*", ".gitignore"]
      - name: Sign extension
        uses: kewisch/action-web-ext@v1.3
        with:
          cmd: sign
          verbose: true
          channel: listed
          sourceCode: ${{ env.PACKAGE_NAME }}
          metaDataFile: metadata.json
          license: MPL-2.0
          apiKey: ${{ secrets.FIREFOX_ISSUER }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.tag }}
          release_name: D R F R F ${{ github.event.inputs.tag }}
          draft: false
          prerelease: false
      - name: Upload release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: package_firefox.zip
          asset_name: release_firefox.zip
          asset_content_type: application/zip


      
          






          
